<?php

use Illuminate\Database\Seeder;

class CountrySeederNew extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        DB::table('countries')->insert(['id' => 1, 'sortname' => 'AF', 'name' => 'Afghanistan']);
        DB::table('countries')->insert(['id' => 2, 'sortname' => 'AL', 'name' => 'Albania']);
        DB::table('countries')->insert(['id' => 3, 'sortname' => 'DZ', 'name' => 'Algeria']);
        DB::table('countries')->insert(['id' => 4, 'sortname' => 'AS', 'name' => 'American Samoa']);
        DB::table('countries')->insert(['id' => 5, 'sortname' => 'AD', 'name' => 'Andorra']);
        DB::table('countries')->insert(['id' => 6, 'sortname' => 'AO', 'name' => 'Angola']);
        DB::table('countries')->insert(['id' => 7, 'sortname' => 'AI', 'name' => 'Anguilla']);
        DB::table('countries')->insert(['id' => 8, 'sortname' => 'AQ', 'name' => 'Antarctica']);
        DB::table('countries')->insert(['id' => 9, 'sortname' => 'AG', 'name' => 'Antigua And Barbuda']);
        DB::table('countries')->insert(['id' => 10, 'sortname' => 'AR', 'name' => 'Argentina']);
        DB::table('countries')->insert(['id' => 11, 'sortname' => 'AM', 'name' => 'Armenia']);
        DB::table('countries')->insert(['id' => 12, 'sortname' => 'AW', 'name' => 'Aruba']);
        DB::table('countries')->insert(['id' => 13, 'sortname' => 'AU', 'name' => 'Australia']);
        DB::table('countries')->insert(['id' => 14, 'sortname' => 'AT', 'name' => 'Austria']);
        DB::table('countries')->insert(['id' => 15, 'sortname' => 'AZ', 'name' => 'Azerbaijan']);
        DB::table('countries')->insert(['id' => 16, 'sortname' => 'BS', 'name' => 'Bahamas The']);
        DB::table('countries')->insert(['id' => 17, 'sortname' => 'BH', 'name' => 'Bahrain']);
        DB::table('countries')->insert(['id' => 18, 'sortname' => 'BD', 'name' => 'Bangladesh']);
        DB::table('countries')->insert(['id' => 19, 'sortname' => 'BB', 'name' => 'Barbados']);
        DB::table('countries')->insert(['id' => 20, 'sortname' => 'BY', 'name' => 'Belarus']);
        DB::table('countries')->insert(['id' => 21, 'sortname' => 'BE', 'name' => 'Belgium']);
        DB::table('countries')->insert(['id' => 22, 'sortname' => 'BZ', 'name' => 'Belize']);
        DB::table('countries')->insert(['id' => 23, 'sortname' => 'BJ', 'name' => 'Benin']);
        DB::table('countries')->insert(['id' => 24, 'sortname' => 'BM', 'name' => 'Bermuda']);
        DB::table('countries')->insert(['id' => 25, 'sortname' => 'BT', 'name' => 'Bhutan']);
        DB::table('countries')->insert(['id' => 26, 'sortname' => 'BO', 'name' => 'Bolivia']);
        DB::table('countries')->insert(['id' => 27, 'sortname' => 'BA', 'name' => 'Bosnia and Herzegovina']);
        DB::table('countries')->insert(['id' => 28, 'sortname' => 'BW', 'name' => 'Botswana']);
        DB::table('countries')->insert(['id' => 29, 'sortname' => 'BV', 'name' => 'Bouvet Island']);
        DB::table('countries')->insert(['id' => 30, 'sortname' => 'BR', 'name' => 'Brazil']);
        DB::table('countries')->insert(['id' => 31, 'sortname' => 'IO', 'name' => 'British Indian Ocean Territory']);
        DB::table('countries')->insert(['id' => 32, 'sortname' => 'BN', 'name' => 'Brunei']);
        DB::table('countries')->insert(['id' => 33, 'sortname' => 'BG', 'name' => 'Bulgaria']);
        DB::table('countries')->insert(['id' => 34, 'sortname' => 'BF', 'name' => 'Burkina Faso']);
        DB::table('countries')->insert(['id' => 35, 'sortname' => 'BI', 'name' => 'Burundi']);
        DB::table('countries')->insert(['id' => 36, 'sortname' => 'KH', 'name' => 'Cambodia']);
        DB::table('countries')->insert(['id' => 37, 'sortname' => 'CM', 'name' => 'Cameroon']);
        DB::table('countries')->insert(['id' => 38, 'sortname' => 'CA', 'name' => 'Canada']);
        DB::table('countries')->insert(['id' => 39, 'sortname' => 'CV', 'name' => 'Cape Verde']);
        DB::table('countries')->insert(['id' => 40, 'sortname' => 'KY', 'name' => 'Cayman Islands']);
        DB::table('countries')->insert(['id' => 41, 'sortname' => 'CF', 'name' => 'Central African Republic']);
        DB::table('countries')->insert(['id' => 42, 'sortname' => 'TD', 'name' => 'Chad']);
        DB::table('countries')->insert(['id' => 43, 'sortname' => 'CL', 'name' => 'Chile']);
        DB::table('countries')->insert(['id' => 44, 'sortname' => 'CN', 'name' => 'China']);
        DB::table('countries')->insert(['id' => 45, 'sortname' => 'CX', 'name' => 'Christmas Island']);
        DB::table('countries')->insert(['id' => 46, 'sortname' => 'CC', 'name' => 'Cocos (Keeling) Islands']);
        DB::table('countries')->insert(['id' => 47, 'sortname' => 'CO', 'name' => 'Colombia']);
        DB::table('countries')->insert(['id' => 48, 'sortname' => 'KM', 'name' => 'Comoros']);
        DB::table('countries')->insert(['id' => 49, 'sortname' => 'CG', 'name' => 'Congo']);
        DB::table('countries')->insert(['id' => 50, 'sortname' => 'CD', 'name' => 'Congo The Democratic Republic Of The']);
        DB::table('countries')->insert(['id' => 51, 'sortname' => 'CK', 'name' => 'Cook Islands']);
        DB::table('countries')->insert(['id' => 52, 'sortname' => 'CR', 'name' => 'Costa Rica']);
        DB::table('countries')->insert(['id' => 53, 'sortname' => 'CI', 'name' => 'Cote D\'Ivoire (Ivory Coast)']);
        DB::table('countries')->insert(['id' => 54, 'sortname' => 'HR', 'name' => 'Croatia (Hrvatska)']);
        DB::table('countries')->insert(['id' => 55, 'sortname' => 'CU', 'name' => 'Cuba']);
        DB::table('countries')->insert(['id' => 56, 'sortname' => 'CY', 'name' => 'Cyprus']);
        DB::table('countries')->insert(['id' => 57, 'sortname' => 'CZ', 'name' => 'Czech Republic']);
        DB::table('countries')->insert(['id' => 58, 'sortname' => 'DK', 'name' => 'Denmark']);
        DB::table('countries')->insert(['id' => 59, 'sortname' => 'DJ', 'name' => 'Djibouti']);
        DB::table('countries')->insert(['id' => 60, 'sortname' => 'DM', 'name' => 'Dominica']);
        DB::table('countries')->insert(['id' => 61, 'sortname' => 'DO', 'name' => 'Dominican Republic']);
        DB::table('countries')->insert(['id' => 62, 'sortname' => 'TP', 'name' => 'East Timor']);
        DB::table('countries')->insert(['id' => 63, 'sortname' => 'EC', 'name' => 'Ecuador']);
        DB::table('countries')->insert(['id' => 64, 'sortname' => 'EG', 'name' => 'Egypt']);
        DB::table('countries')->insert(['id' => 65, 'sortname' => 'SV', 'name' => 'El Salvador']);
        DB::table('countries')->insert(['id' => 66, 'sortname' => 'GQ', 'name' => 'Equatorial Guinea']);
        DB::table('countries')->insert(['id' => 67, 'sortname' => 'ER', 'name' => 'Eritrea']);
        DB::table('countries')->insert(['id' => 68, 'sortname' => 'EE', 'name' => 'Estonia']);
        DB::table('countries')->insert(['id' => 69, 'sortname' => 'ET', 'name' => 'Ethiopia']);
        DB::table('countries')->insert(['id' => 70, 'sortname' => 'XA', 'name' => 'External Territories of Australia']);
        DB::table('countries')->insert(['id' => 71, 'sortname' => 'FK', 'name' => 'Falkland Islands']);
        DB::table('countries')->insert(['id' => 72, 'sortname' => 'FO', 'name' => 'Faroe Islands']);
        DB::table('countries')->insert(['id' => 73, 'sortname' => 'FJ', 'name' => 'Fiji Islands']);
        DB::table('countries')->insert(['id' => 74, 'sortname' => 'FI', 'name' => 'Finland']);
        DB::table('countries')->insert(['id' => 75, 'sortname' => 'FR', 'name' => 'France']);
        DB::table('countries')->insert(['id' => 76, 'sortname' => 'GF', 'name' => 'French Guiana']);
        DB::table('countries')->insert(['id' => 77, 'sortname' => 'PF', 'name' => 'French Polynesia']);
        DB::table('countries')->insert(['id' => 78, 'sortname' => 'TF', 'name' => 'French Southern Territories']);
        DB::table('countries')->insert(['id' => 79, 'sortname' => 'GA', 'name' => 'Gabon']);
        DB::table('countries')->insert(['id' => 80, 'sortname' => 'GM', 'name' => 'Gambia The']);
        DB::table('countries')->insert(['id' => 81, 'sortname' => 'GE', 'name' => 'Georgia']);
        DB::table('countries')->insert(['id' => 82, 'sortname' => 'DE', 'name' => 'Germany']);
        DB::table('countries')->insert(['id' => 83, 'sortname' => 'GH', 'name' => 'Ghana']);
        DB::table('countries')->insert(['id' => 84, 'sortname' => 'GI', 'name' => 'Gibraltar']);
        DB::table('countries')->insert(['id' => 85, 'sortname' => 'GR', 'name' => 'Greece']);
        DB::table('countries')->insert(['id' => 86, 'sortname' => 'GL', 'name' => 'Greenland']);
        DB::table('countries')->insert(['id' => 87, 'sortname' => 'GD', 'name' => 'Grenada']);
        DB::table('countries')->insert(['id' => 88, 'sortname' => 'GP', 'name' => 'Guadeloupe']);
        DB::table('countries')->insert(['id' => 89, 'sortname' => 'GU', 'name' => 'Guam']);
        DB::table('countries')->insert(['id' => 90, 'sortname' => 'GT', 'name' => 'Guatemala']);
        DB::table('countries')->insert(['id' => 91, 'sortname' => 'XU', 'name' => 'Guernsey and Alderney']);
        DB::table('countries')->insert(['id' => 92, 'sortname' => 'GN', 'name' => 'Guinea']);
        DB::table('countries')->insert(['id' => 93, 'sortname' => 'GW', 'name' => 'Guinea-Bissau']);
        DB::table('countries')->insert(['id' => 94, 'sortname' => 'GY', 'name' => 'Guyana']);
        DB::table('countries')->insert(['id' => 95, 'sortname' => 'HT', 'name' => 'Haiti']);
        DB::table('countries')->insert(['id' => 96, 'sortname' => 'HM', 'name' => 'Heard and McDonald Islands']);
        DB::table('countries')->insert(['id' => 97, 'sortname' => 'HN', 'name' => 'Honduras']);
        DB::table('countries')->insert(['id' => 98, 'sortname' => 'HK', 'name' => 'Hong Kong S.A.R.']);
        DB::table('countries')->insert(['id' => 99, 'sortname' => 'HU', 'name' => 'Hungary']);
        DB::table('countries')->insert(['id' => 100, 'sortname' =>  'IS', 'name' => 'Iceland']);
        DB::table('countries')->insert(['id' => 101, 'sortname' =>  'IN', 'name' => 'India']);
        DB::table('countries')->insert(['id' => 102, 'sortname' =>  'ID', 'name' => 'Indonesia']);
        DB::table('countries')->insert(['id' => 103, 'sortname' =>  'IR', 'name' => 'Iran']);
        DB::table('countries')->insert(['id' => 104, 'sortname' =>  'IQ', 'name' => 'Iraq']);
        DB::table('countries')->insert(['id' => 105, 'sortname' =>  'IE', 'name' => 'Ireland']);
        DB::table('countries')->insert(['id' => 106, 'sortname' =>  'IL', 'name' => 'Israel']);
        DB::table('countries')->insert(['id' => 107, 'sortname' =>  'IT', 'name' => 'Italy']);
        DB::table('countries')->insert(['id' => 108, 'sortname' =>  'JM', 'name' => 'Jamaica']);
        DB::table('countries')->insert(['id' => 109, 'sortname' =>  'JP', 'name' => 'Japan']);
        DB::table('countries')->insert(['id' => 110, 'sortname' =>  'XJ', 'name' => 'Jersey']);
        DB::table('countries')->insert(['id' => 111, 'sortname' =>  'JO', 'name' => 'Jordan']);
        DB::table('countries')->insert(['id' => 112, 'sortname' =>  'KZ', 'name' => 'Kazakhstan']);
        DB::table('countries')->insert(['id' => 113, 'sortname' =>  'KE', 'name' => 'Kenya']);
        DB::table('countries')->insert(['id' => 114, 'sortname' =>  'KI', 'name' => 'Kiribati']);
        DB::table('countries')->insert(['id' => 115, 'sortname' =>  'KP', 'name' => 'Korea North']);
        DB::table('countries')->insert(['id' => 116, 'sortname' =>  'KR', 'name' => 'Korea South']);
        DB::table('countries')->insert(['id' => 117, 'sortname' =>  'KW', 'name' => 'Kuwait']);
        DB::table('countries')->insert(['id' => 118, 'sortname' =>  'KG', 'name' => 'Kyrgyzstan']);
        DB::table('countries')->insert(['id' => 119, 'sortname' =>  'LA', 'name' => 'Laos']);
        DB::table('countries')->insert(['id' => 120, 'sortname' =>  'LV', 'name' => 'Latvia']);
        DB::table('countries')->insert(['id' => 121, 'sortname' =>  'LB', 'name' => 'Lebanon']);
        DB::table('countries')->insert(['id' => 122, 'sortname' =>  'LS', 'name' => 'Lesotho']);
        DB::table('countries')->insert(['id' => 123, 'sortname' =>  'LR', 'name' => 'Liberia']);
        DB::table('countries')->insert(['id' => 124, 'sortname' =>  'LY', 'name' => 'Libya']);
        DB::table('countries')->insert(['id' => 125, 'sortname' =>  'LI', 'name' => 'Liechtenstein']);
        DB::table('countries')->insert(['id' => 126, 'sortname' =>  'LT', 'name' => 'Lithuania']);
        DB::table('countries')->insert(['id' => 127, 'sortname' =>  'LU', 'name' => 'Luxembourg']);
        DB::table('countries')->insert(['id' => 128, 'sortname' =>  'MO', 'name' => 'Macau S.A.R.']);
        DB::table('countries')->insert(['id' => 129, 'sortname' =>  'MK', 'name' => 'Macedonia']);
        DB::table('countries')->insert(['id' => 130, 'sortname' =>  'MG', 'name' => 'Madagascar']);
        DB::table('countries')->insert(['id' => 131, 'sortname' =>  'MW', 'name' => 'Malawi']);
        DB::table('countries')->insert(['id' => 132, 'sortname' =>  'MY', 'name' => 'Malaysia']);
        DB::table('countries')->insert(['id' => 133, 'sortname' =>  'MV', 'name' => 'Maldives']);
        DB::table('countries')->insert(['id' => 134, 'sortname' =>  'ML', 'name' => 'Mali']);
        DB::table('countries')->insert(['id' => 135, 'sortname' =>  'MT', 'name' => 'Malta']);
        DB::table('countries')->insert(['id' => 136, 'sortname' =>  'XM', 'name' => 'Man (Isle of)']);
        DB::table('countries')->insert(['id' => 137, 'sortname' =>  'MH', 'name' => 'Marshall Islands']);
        DB::table('countries')->insert(['id' => 138, 'sortname' =>  'MQ', 'name' => 'Martinique']);
        DB::table('countries')->insert(['id' => 139, 'sortname' =>  'MR', 'name' => 'Mauritania']);
        DB::table('countries')->insert(['id' => 140, 'sortname' =>  'MU', 'name' => 'Mauritius']);
        DB::table('countries')->insert(['id' => 141, 'sortname' =>  'YT', 'name' => 'Mayotte']);
        DB::table('countries')->insert(['id' => 142, 'sortname' =>  'MX', 'name' => 'Mexico']);
        DB::table('countries')->insert(['id' => 143, 'sortname' =>  'FM', 'name' => 'Micronesia']);
        DB::table('countries')->insert(['id' => 144, 'sortname' =>  'MD', 'name' => 'Moldova']);
        DB::table('countries')->insert(['id' => 145, 'sortname' =>  'MC', 'name' => 'Monaco']);
        DB::table('countries')->insert(['id' => 146, 'sortname' =>  'MN', 'name' => 'Mongolia']);
        DB::table('countries')->insert(['id' => 147, 'sortname' =>  'MS', 'name' => 'Montserrat']);
        DB::table('countries')->insert(['id' => 148, 'sortname' =>  'MA', 'name' => 'Morocco']);
        DB::table('countries')->insert(['id' => 149, 'sortname' =>  'MZ', 'name' => 'Mozambique']);
        DB::table('countries')->insert(['id' => 150, 'sortname' =>  'MM', 'name' => 'Myanmar']);
        DB::table('countries')->insert(['id' => 151, 'sortname' =>  'NA', 'name' => 'Namibia']);
        DB::table('countries')->insert(['id' => 152, 'sortname' =>  'NR', 'name' => 'Nauru']);
        DB::table('countries')->insert(['id' => 153, 'sortname' =>  'NP', 'name' => 'Nepal']);
        DB::table('countries')->insert(['id' => 154, 'sortname' =>  'AN', 'name' => 'Netherlands Antilles']);
        DB::table('countries')->insert(['id' => 155, 'sortname' =>  'NL', 'name' => 'Netherlands The']);
        DB::table('countries')->insert(['id' => 156, 'sortname' =>  'NC', 'name' => 'New Caledonia']);
        DB::table('countries')->insert(['id' => 157, 'sortname' =>  'NZ', 'name' => 'New Zealand']);
        DB::table('countries')->insert(['id' => 158, 'sortname' =>  'NI', 'name' => 'Nicaragua']);
        DB::table('countries')->insert(['id' => 159, 'sortname' =>  'NE', 'name' => 'Niger']);
        DB::table('countries')->insert(['id' => 160, 'sortname' =>  'NG', 'name' => 'Nigeria']);
        DB::table('countries')->insert(['id' => 161, 'sortname' =>  'NU', 'name' => 'Niue']);
        DB::table('countries')->insert(['id' => 162, 'sortname' =>  'NF', 'name' => 'Norfolk Island']);
        DB::table('countries')->insert(['id' => 163, 'sortname' =>  'MP', 'name' => 'Northern Mariana Islands']);
        DB::table('countries')->insert(['id' => 164, 'sortname' =>  'NO', 'name' => 'Norway']);
        DB::table('countries')->insert(['id' => 165, 'sortname' =>  'OM', 'name' => 'Oman']);
        DB::table('countries')->insert(['id' => 166, 'sortname' =>  'PK', 'name' => 'Pakistan']);
        DB::table('countries')->insert(['id' => 167, 'sortname' =>  'PW', 'name' => 'Palau']);
        DB::table('countries')->insert(['id' => 168, 'sortname' =>  'PS', 'name' => 'Palestinian Territory Occupied']);
        DB::table('countries')->insert(['id' => 169, 'sortname' =>  'PA', 'name' => 'Panama']);
        DB::table('countries')->insert(['id' => 170, 'sortname' =>  'PG', 'name' => 'Papua new Guinea']);
        DB::table('countries')->insert(['id' => 171, 'sortname' =>  'PY', 'name' => 'Paraguay']);
        DB::table('countries')->insert(['id' => 172, 'sortname' =>  'PE', 'name' => 'Peru']);
        DB::table('countries')->insert(['id' => 173, 'sortname' =>  'PH', 'name' => 'Philippines']);
        DB::table('countries')->insert(['id' => 174, 'sortname' =>  'PN', 'name' => 'Pitcairn Island']);
        DB::table('countries')->insert(['id' => 175, 'sortname' =>  'PL', 'name' => 'Poland']);
        DB::table('countries')->insert(['id' => 176, 'sortname' =>  'PT', 'name' => 'Portugal']);
        DB::table('countries')->insert(['id' => 177, 'sortname' =>  'PR', 'name' => 'Puerto Rico']);
        DB::table('countries')->insert(['id' => 178, 'sortname' =>  'QA', 'name' => 'Qatar']);
        DB::table('countries')->insert(['id' => 179, 'sortname' =>  'RE', 'name' => 'Reunion']);
        DB::table('countries')->insert(['id' => 180, 'sortname' =>  'RO', 'name' => 'Romania']);
        DB::table('countries')->insert(['id' => 181, 'sortname' =>  'RU', 'name' => 'Russia']);
        DB::table('countries')->insert(['id' => 182, 'sortname' =>  'RW', 'name' => 'Rwanda']);
        DB::table('countries')->insert(['id' => 183, 'sortname' =>  'SH', 'name' => 'Saint Helena']);
        DB::table('countries')->insert(['id' => 184, 'sortname' =>  'KN', 'name' => 'Saint Kitts And Nevis']);
        DB::table('countries')->insert(['id' => 185, 'sortname' =>  'LC', 'name' => 'Saint Lucia']);
        DB::table('countries')->insert(['id' => 186, 'sortname' =>  'PM', 'name' => 'Saint Pierre and Miquelon']);
        DB::table('countries')->insert(['id' => 187, 'sortname' =>  'VC', 'name' => 'Saint Vincent And The Grenadines']);
        DB::table('countries')->insert(['id' => 188, 'sortname' =>  'WS', 'name' => 'Samoa']);
        DB::table('countries')->insert(['id' => 189, 'sortname' =>  'SM', 'name' => 'San Marino']);
        DB::table('countries')->insert(['id' => 190, 'sortname' =>  'ST', 'name' => 'Sao Tome and Principe']);
        DB::table('countries')->insert(['id' => 191, 'sortname' =>  'SA', 'name' => 'Saudi Arabia']);
        DB::table('countries')->insert(['id' => 192, 'sortname' =>  'SN', 'name' => 'Senegal']);
        DB::table('countries')->insert(['id' => 193, 'sortname' =>  'RS', 'name' => 'Serbia']);
        DB::table('countries')->insert(['id' => 194, 'sortname' =>  'SC', 'name' => 'Seychelles']);
        DB::table('countries')->insert(['id' => 195, 'sortname' =>  'SL', 'name' => 'Sierra Leone']);
        DB::table('countries')->insert(['id' => 196, 'sortname' =>  'SG', 'name' => 'Singapore']);
        DB::table('countries')->insert(['id' => 197, 'sortname' =>  'SK', 'name' => 'Slovakia']);
        DB::table('countries')->insert(['id' => 198, 'sortname' =>  'SI', 'name' => 'Slovenia']);
        DB::table('countries')->insert(['id' => 199, 'sortname' =>  'XG', 'name' => 'Smaller Territories of the UK']);
        DB::table('countries')->insert(['id' => 200, 'sortname' =>  'SB', 'name' => 'Solomon Islands']);
        DB::table('countries')->insert(['id' => 201, 'sortname' =>  'SO', 'name' => 'Somalia']);
        DB::table('countries')->insert(['id' => 202, 'sortname' =>  'ZA', 'name' => 'South Africa']);
        DB::table('countries')->insert(['id' => 203, 'sortname' =>  'GS', 'name' => 'South Georgia']);
        DB::table('countries')->insert(['id' => 204, 'sortname' =>  'SS', 'name' => 'South Sudan']);
        DB::table('countries')->insert(['id' => 205, 'sortname' =>  'ES', 'name' => 'Spain']);
        DB::table('countries')->insert(['id' => 206, 'sortname' =>  'LK', 'name' => 'Sri Lanka']);
        DB::table('countries')->insert(['id' => 207, 'sortname' =>  'SD', 'name' => 'Sudan']);
        DB::table('countries')->insert(['id' => 208, 'sortname' =>  'SR', 'name' => 'Suriname']);
        DB::table('countries')->insert(['id' => 209, 'sortname' =>  'SJ', 'name' => 'Svalbard And Jan Mayen Islands']);
        DB::table('countries')->insert(['id' => 210, 'sortname' =>  'SZ', 'name' => 'Swaziland']);
        DB::table('countries')->insert(['id' => 211, 'sortname' =>  'SE', 'name' => 'Sweden']);
        DB::table('countries')->insert(['id' => 212, 'sortname' =>  'CH', 'name' => 'Switzerland']);
        DB::table('countries')->insert(['id' => 213, 'sortname' =>  'SY', 'name' => 'Syria']);
        DB::table('countries')->insert(['id' => 214, 'sortname' =>  'TW', 'name' => 'Taiwan']);
        DB::table('countries')->insert(['id' => 215, 'sortname' =>  'TJ', 'name' => 'Tajikistan']);
        DB::table('countries')->insert(['id' => 216, 'sortname' =>  'TZ', 'name' => 'Tanzania']);
        DB::table('countries')->insert(['id' => 217, 'sortname' =>  'TH', 'name' => 'Thailand']);
        DB::table('countries')->insert(['id' => 218, 'sortname' =>  'TG', 'name' => 'Togo']);
        DB::table('countries')->insert(['id' => 219, 'sortname' =>  'TK', 'name' => 'Tokelau']);
        DB::table('countries')->insert(['id' => 220, 'sortname' =>  'TO', 'name' => 'Tonga']);
        DB::table('countries')->insert(['id' => 221, 'sortname' =>  'TT', 'name' => 'Trinidad And Tobago']);
        DB::table('countries')->insert(['id' => 222, 'sortname' =>  'TN', 'name' => 'Tunisia']);
        DB::table('countries')->insert(['id' => 223, 'sortname' =>  'TR', 'name' => 'Turkey']);
        DB::table('countries')->insert(['id' => 224, 'sortname' =>  'TM', 'name' => 'Turkmenistan']);
        DB::table('countries')->insert(['id' => 225, 'sortname' =>  'TC', 'name' => 'Turks And Caicos Islands']);
        DB::table('countries')->insert(['id' => 226, 'sortname' =>  'TV', 'name' => 'Tuvalu']);
        DB::table('countries')->insert(['id' => 227, 'sortname' =>  'UG', 'name' => 'Uganda']);
        DB::table('countries')->insert(['id' => 228, 'sortname' =>  'UA', 'name' => 'Ukraine']);
        DB::table('countries')->insert(['id' => 229, 'sortname' =>  'AE', 'name' => 'United Arab Emirates']);
        DB::table('countries')->insert(['id' => 230, 'sortname' =>  'GB', 'name' => 'United Kingdom']);
        DB::table('countries')->insert(['id' => 231, 'sortname' =>  'US', 'name' => 'United States']);
        DB::table('countries')->insert(['id' => 232, 'sortname' =>  'UM', 'name' => 'United States Minor Outlying Islands']);
        DB::table('countries')->insert(['id' => 233, 'sortname' =>  'UY', 'name' => 'Uruguay']);
        DB::table('countries')->insert(['id' => 234, 'sortname' =>  'UZ', 'name' => 'Uzbekistan']);
        DB::table('countries')->insert(['id' => 235, 'sortname' =>  'VU', 'name' => 'Vanuatu']);
        DB::table('countries')->insert(['id' => 236, 'sortname' =>  'VA', 'name' => 'Vatican City State (Holy See)']);
        DB::table('countries')->insert(['id' => 237, 'sortname' =>  'VE', 'name' => 'Venezuela']);
        DB::table('countries')->insert(['id' => 238, 'sortname' =>  'VN', 'name' => 'Vietnam']);
        DB::table('countries')->insert(['id' => 239, 'sortname' =>  'VG', 'name' => 'Virgin Islands (British)']);
        DB::table('countries')->insert(['id' => 240, 'sortname' =>  'VI', 'name' => 'Virgin Islands (US)']);
        DB::table('countries')->insert(['id' => 241, 'sortname' =>  'WF', 'name' => 'Wallis And Futuna Islands']);
        DB::table('countries')->insert(['id' => 242, 'sortname' =>  'EH', 'name' => 'Western Sahara']);
        DB::table('countries')->insert(['id' => 243, 'sortname' =>  'YE', 'name' => 'Yemen']);
        DB::table('countries')->insert(['id' => 244, 'sortname' =>  'YU', 'name' => 'Yugoslavia']);
        DB::table('countries')->insert(['id' => 245, 'sortname' =>  'ZM', 'name' => 'Zambia']);
        DB::table('countries')->insert(['id' => 246, 'sortname' =>  'ZW', 'name' => 'Zimbabwe']);
    }
}
